<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Control.aspx.cs" Inherits="trythis.Control" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">

        .imgclick:active{
            box-shadow: 0 5px #666;
            transform: translateY(4px);
        }
        .imgclick:hover{
            -webkit-border-radius: 10px;
    -moz-border-radius: 10px;
    border-radius: 10px;
 -webkit-box-shadow: 0px 0px 30px 0px rgba(0, 0, 245, 0.67);
-moz-box-shadow:    0px 0px 30px 0px rgba(0, 0, 245, 0.67);
box-shadow:         0px 0px 30px 0px rgba(0, 0, 245, 0.67);
        }
       [type=radio] { 
  position: absolute;
  opacity: 0;
  width: 0;
  height: 0;
}

/* IMAGE STYLES */
[type=radio] + img {
  cursor: pointer;
}

/* CHECKED STYLES */
[type=radio]:checked + img {
  outline: 2px solid #f00;
}
    </style>
      <link href="Content/ButtonsForControl.css" rel="stylesheet" />
    <link href="Content/style-responsive.css" rel="stylesheet" />
    <link href="Content/font-awesome.css" rel="stylesheet" />
    <link href="Content/style.css" rel="stylesheet" />
    <link href="Content/ControlStyle.css" rel="stylesheet" />
    
    <!--Reference the SignalR library. -->
        <script src="Scripts/jquery-3.3.1.min.js" type="text/javascript"></script>
        <script src="Scripts/jquery.signalR-2.3.0.js"></script>
        <script src="Scripts/jquery.signalR-2.3.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
   <script src='<%: ResolveClientUrl("~/signalr/hubs") %>' ></script> 
    <script src="Scripts/ControlKeys.js" >
       
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="divopt">
        <asp:TextBox Visible="false" ID="ipAddressToSend" runat="server"></asp:TextBox>
        <asp:ScriptManagerProxy ID="ScriptManagerProxy1" runat="server" ></asp:ScriptManagerProxy>
        <asp:UpdatePanel runat="server" ID="updateControl" >
            <ContentTemplate>
        <div  >
        <table>
        <tr>
        <td>
        <div class="col-md-3 col " style="width:300px">
            
            <asp:Panel ID="Panel1" runat="server"  Height="290" Width="290" BackColor="#dfdcdc"  BorderStyle="None">
          
                <table style=" height:270px; width:270px">
                    
                        <tr style=" background-color:#ccd1d9; ">                        
                        <td colspan="6" style="font-size:medium; font-weight:bold; color:black; text-align:center"><h4>System Control</h4></td>                    
                        </tr>
                    
                    <tr >
                        <td colspan="3" style="font-size:small; text-align:center"> System Power</td>
                        <td colspan="3" style="font-size:small; text-align:center"> Computer Power</td>
                    </tr>
                    <tr style="align-items:center; align-content:center;">
                        <td colspan="3" style="text-align:center">
                            
                            <input type="image" height="70" width="70" src="Images/powerOff.png" class="imgclick"    id="systempower" />
                            </td>
                        <td colspan="3" style="text-align:center">
                            <input type="image" height="70" width="70" src="Images/powerOff.png" class="imgclick" id="pcpower" /></td>                    
                    </tr>
                
                                
                    <tr >
                        <td colspan="2" style="text-align:center">
                            <input type="image" class="imgclick" src="Images/unlock.png" Height="50" width="50" id="syslock" />
                           </td>
                        <td colspan="2" style="text-align:center"  >
                            <input type="image" class="imgclick" src="Images/unlock.png" Height="50" width="50" id="podiumlock"/>
                            </td>
                        <td colspan="2" style="text-align:center" >
                            <input type="image" class="imgclick" src="Images/unlock.png" Height="50" width="50" id="classlock"/>
                             </td>
                    </tr>
                    <tr >
                        <td colspan="2" style="font-size:small; text-align:center">system lock</td>
                        <td colspan="2" style="font-size:small; text-align:center" >podium lock</td>
                        <td colspan="2" style="font-size:small; text-align:center">class lock</td>
                    </tr>
                </table>            
            </asp:Panel>
                </div>        
        </td>
        <td>
        <div class="col-md-3 col " style=" width:300px">
            
            <asp:Panel ID="Panel2" runat="server" Height="290" Width="290" BackColor="#dfdcdc" BorderStyle="none">

                <table style=" height:270px; width:270px">
                    <tr style=" background-color:#ccd1d9;" >
                        <td colspan="2" style="font-size:medium; font-weight:bold; color:black; text-align:center"><h4>Projector Control</h4></td>
                    </tr>
                    <tr style="width:220px">
                        <td style="text-align:center">
                            <input  type="image" src="Images/power.png" class="imgclick" Height="50" width="50" id="projectorOn"/>
                        </td>
                        <td style="text-align:center">
                            <input type="image" src="Images/HDMI.png" class="imgclick" Height="50" width="50" id="hdmi"/>
                        </td>
                    </tr>
                    <tr style="width:220px">
                        <td style="text-align:center">
                            <input type="image" src="Images/power.png" class="imgclick" Height="50" width="50" id="projectorOff"/>
                        </td>
                        <td style="text-align:center">
                            <input type="image" src="Images/video.png" class="imgclick" Height="50" width="50" id="projVideo"/></td>
                    </tr>
                    <tr style="width:220px">
                        <td style="text-align:center">
                            <input type="image" src="Images/stop.png" class="imgclick" Height="50" width="50" id="projSleep"/></td>
                        <td style="text-align:center">
                            <input type="image" src="Images/VGA.png" class="imgclick" Height="50" width="50" id="vga"/> </td>
                    </tr>                
                </table>
            </asp:Panel>
                
        </div>
        </td>
        <td>
        <div class="col-md-3 col" style=" width:200px">
            <asp:Panel ID="Panel3" runat="server" Height="290" Width="150" BackColor="#dfdcdc"  BorderStyle="None">
                <table style="width:130px; height:270px;">
                    <tr style=" background-color:#ccd1d9;">
                        <td colspan="2" style="font-size:medium; font-weight:bold; color:black; text-align:center"><h4>Light Control</h4></td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <input type="image" src="Images/light.png" class="imgclick" Height="50" width="50" id="light1"/> </td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <input type="image" src="Images/light.png" class="imgclick" Height="50" width="50" id="light2"/> </td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <input type="image" src="Images/light.png" class="imgclick" Height="50" width="50" id="light"/></td>
                    </tr>
                </table>
            </asp:Panel>
        </div>
        </td>            
        <td rowspan="2">
        <div  style=" width:200px"> 
            <asp:Panel ID="Panel9" runat="server" Height="600" Width="150" BackColor="#dfdcdc" BorderStyle="None">
                <table style="width:130px; height:580px;">
                    <tr style=" background-color:#ccd1d9;" >
                        <td colspan="2" style="font-size:medium; font-weight:bold; color:black; text-align:center"><h4>Media Control</h4></td>
                    </tr>
                    <tr  style="width:130px;">
                        <td  style="text-align:center">
                            <label>
                            <input type="radio" name="test" id="desktop" checked>
                            <img src="Images/Desktop.png" Height="50" width="50" class="imgclick">
                            </label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%--<input type="image" src="Images/Desktop.png" class="imgclick" Height="50" width="50" id="desktop"/>--%></td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <label>
                            <input type="radio" name="test" id="laptop" checked>
                            <img src="Images/laptop.png" Height="50" width="50" class="imgclick">
                            </label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%--<input type="image" src="Images/laptop.png" class="imgclick" Height="50" width="50" id="laptop"/>--%></td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <label>
                            <input type="radio" name="test" id="platform" checked>
                            <img src="Images/platform.png" Height="50" width="50" class="imgclick">
                            </label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%--<input type="image" src="Images/platform.png" class="imgclick" Height="50" width="50" id="platform"/>--%></td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center" >
                            <%--<input type="image" src="Images/platform.png" class="imgclick" Height="50" width="50" id="digitalEquipment"/>--%> 
                             <label>
                            <input type="radio" name="test" id="digitalEquipment" checked>
                            <img src="Images/platform.png" Height="50" width="50" class="imgclick">
                            </label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <%--<input type="image" src="Images/DVD.png" class="imgclick" Height="50" width="50" id="dvd"/>--%> 
                            <label>
                            <input type="radio" name="test" id="dvd" checked>
                            <img src="Images/DVD.png" Height="50" width="50" class="imgclick">
                            </label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <%--<input type="image" src="Images/Blu-Ray.png" class="imgclick" Height="50" width="50" id="bluray"/>--%>
                            <label>
                            <input type="radio" name="test" id="bluray" checked>
                            <img src="Images/Blu-Ray.png" Height="50" width="50" class="imgclick">
                            </label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    </tr>
                    <tr  style="width:130px;">
                        <td  style="text-align:center">
                           <%--<input type="image" src="Images/TV.png" class="imgclick" Height="50" width="50" id="tv"/>--%>
                            <label>
                            <input type="radio" name="test" id="tv" checked>
                            <img src="Images/TV.png" Height="50" width="50" class="imgclick">
                            </label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center">
                            <%--<input type="image" src="Images/Camera.png" class="imgclick" Height="50" width="50" id="camera"/>--%>
                        <label>
                            <input type="radio" name="test" id="camera" checked>
                            <img src="Images/Camera.png" Height="50" width="50" class="imgclick">
                            </label>    
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                            </tr>
                    <tr  style="width:130px;">
                        <td style="text-align:center" >
                            <%--<input type="image" src="Images/video.png" class="imgclick" Height="50" width="50" id="Recorder"/>--%>
                        <label>
                            <input type="radio" name="test" id="recorder" checked>
                            <img src="Images/video.png" Height="50" width="50" class="imgclick">
                            </label>    
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
                </table>

            </asp:Panel>
        </div>
        </td>       
        </tr>
        <tr>
        <td>
        <div class="col-md-3 col" style="width:300px">
        <asp:Panel ID="Panel4" runat="server" Height="290" Width="290" BackColor="#dfdcdc" BorderStyle="None">
             <table style="width:270px; height:270px;">
                 <tr style=" background-color:#ccd1d9;">
                    <td colspan="2" style="font-size:medium; font-weight:bold; color:black; text-align:center"><h4>Screen & Curtain Control</h4></td>
                </tr>
                 <tr  >
                    <td  style=" font-size:small; text-align:center">
                        Digital Screen                        
                    </td>
                    <td style=" font-size:small; text-align:center">
                       Digital Curtain
                    </td>
                </tr>
                <tr  >
                    <td  style="text-align:center">
                        <input type="image" src="Images/up.PNG" class="imgclick" Height="50" width="50" id="dsup"  />
                       <%-- <asp:ImageButton ID="dsUp" CssClass="RoundButton" runat="server"  ImageUrl="~/Images/up.PNG" Height="40" Width="80" />--%>
                        
                    </td>
                    <td style="text-align:center">
                        <input type="image" src="Images/open.PNG" class="imgclick" Height="50" width="50" id="dcopen" />
                        <%--<asp:ImageButton ID="dcOpen" CssClass="RoundButton" runat="server"  ImageUrl="~/Images/oepn.PNG" Height="40" Width="80" />--%>
                    </td>
                </tr>
                 <tr>
                    <td  style="text-align:center">
                        <input type="image" src="Images/stop.PNG" class="imgclick" Height="50" width="50" id="dsstop" />
                        <%--<asp:ImageButton ID="dsStop" CssClass="RoundButton" runat="server"  ImageUrl="~/Images/stop.PNG" Height="50" Width="80" />--%>
                    </td>
                    <td style="text-align:center">
                        <input type="image" src="Images/stop.PNG" class="imgclick" Height="50" width="50" id="dcstop" />
                       <%--<asp:ImageButton ID="dcStop" CssClass="RoundButton" runat="server"  ImageUrl="~/Images/stop.PNG" Height="50" Width="80"/>--%>
                    </td>
                     </tr>
                      <tr >
                    <td style="text-align:center">
                        <input type="image" src="Images/down.PNG" class="imgclick" Height="50" width="50" id="dsdown" />
                       <%--<asp:ImageButton ID="dsDown" CssClass="RoundButton" runat="server"  ImageUrl="~/Images/down.PNG" Height="50" Width="80"/>--%>
                    </td>
                    <td  style="text-align:center">
                        <input type="image" src="Images/close.PNG" class="imgclick" Height="50" width="50" id="dcclose" />
                        <%--<asp:ImageButton ID="dcClose" CssClass="RoundButton" runat="server"  ImageUrl="~/Images/close.PNG" Height="50" Width="80" />--%>
                    </td>
                </tr>                
            </table>
        </asp:Panel>
    </div>
        </td>
        <td>
    <div class="col-md-3 col" style=" width:290px">
        <asp:Panel ID="Panel5" runat="server" Height="290" Width="290" BackColor="#dfdcdc"  BorderStyle="None">
             <table style="width:270px; height:270px;">
                 <tr style=" background-color:#ccd1d9;"  >
                    <td colspan="2" style="font-size:medium; font-weight:bold; color:black; text-align:center"><h4>Microphone Control</h4></td>
                </tr>
                <tr  >
                    <td style="text-align:center">
                        <asp:Label ID="Label1" runat="server" Text="Wired Mic" Font-Size="Small"  ></asp:Label>
                    </td>
                    <td style="text-align:center">
                        <asp:Label ID="Label2" runat="server" Text="Wireless Mic" Font-Size="Small" ></asp:Label>
                    </td>
                    </tr>
                 <tr >
                    <td style="text-align:center" >
                        <input type="image" src="Images/volplus.PNG" class="imgclick" Height="50" width="50" id="wiredvolplus" /> </td>
                    <td style="text-align:center">
                       <input type="image" src="Images/volplus.PNG" class="imgclick" Height="50" width="50" id="wirelessvolplus" /> </td>
                </tr>
                 <tr >
                     
                    <td style="text-align:center">
                       <input type="image" src="Images/volminus.PNG" class="imgclick" Height="50" width="50" id="wiredvolminus" /> </td>
                    <td style="text-align:center">
                       <input type="image" src="Images/volminus.PNG" class="imgclick" Height="50" width="50" id="wirelessvolminus" /> </td>
                     </tr>
                       <tr >
                    <td style="text-align:center" class="auto-style1">
                       <input type="image" src="Images/mute.PNG" class="imgclick" Height="50" width="50" id="wiredmute" /> </td>
                     <td style="text-align:center" class="auto-style1">
                       <input type="image" src="Images/mute.PNG" class="imgclick" Height="50" width="50" id="wirelessmute" /> </td>
                </tr>
                
            </table>
        </asp:Panel>
    </div>
        </td>
        <td>
    <div class="col-md-3 col" style=" width:200px">
        <asp:Panel ID="Panel6" runat="server" Height="290" Width="150" BackColor="#dfdcdc" BorderStyle="None">
         <table style="width:130px; height:270px;">
                <tr style=" background-color:#ccd1d9;" >
                    <td style="font-size:medium; font-weight:bold; color:black; text-align:center"><h4>Volume Control</h4></td>
                </tr>
                <tr  >
                    <td style="text-align:center" >
                         <input type="image" src="Images/volplus.PNG" class="imgclick" Height="50" width="50" id="volplus" />
                        
                    </td>
                    </tr>
                 <tr  >
                    <td style="text-align:center">
                       <input type="image" src="Images/volminus.PNG" class="imgclick" Height="50" width="50" id="volminus" />
                         </tr>
                 <tr  >
                    <td style="text-align:center">
                        
                        <input type="image" src="Images/mute.PNG" class="imgclick" Height="50" width="50" id="mute" />
                        </td>
                </tr>
            </table>

        </asp:Panel>
    </div>
        </td>
           </tr>

    </table>
            </div>
        <div  style="display:inline-block; float:left">
    
        <asp:Panel ID="Panel8" runat="server" Height="300" Width="250" BackColor="#dfdcdc"  BorderStyle="None" >
            
             <table style="width:240px; height:256px;" >
                 
                <tr>
                    <td >
                        <asp:ImageButton ID="dvdpower" runat="server" class="imgclick"  ImageUrl="~/Images/button_power.png" Height="50" Width="70" />
                        
                    </td>
                    <td >
                        <asp:ImageButton ID="dvdopen" runat="server" class="imgclick"  ImageUrl="~/Images/button_open.png" Height="50" Width="70" />
                    </td>
                </tr>
                 <tr>
                    <td >
                        <asp:ImageButton ID="dvdstop" runat="server" class="imgclick"  ImageUrl="~/Images/button_stop.png" Height="50" Width="70" />
                    </td>
                    <td >
                       <asp:ImageButton ID="dvdplay" runat="server"  ImageUrl="~/Images/button_play.png" Height="50" Width="70"/>
                    </td>
                     </tr>
                      <tr>
                    <td >
                       <asp:ImageButton ID="dvdprevious" runat="server"  ImageUrl="~/Images/button_previous.png" Height="50" Width="70"/>
                    </td>
                    <td  >
                        <asp:ImageButton ID="dvdnext" runat="server"  ImageUrl="~/Images/button_next.png" Height="50" Width="70" />
                    </td>
                </tr>
                 <tr>
                    <td >
                       <asp:ImageButton ID="dvdpause" runat="server"  ImageUrl="~/Images/button_pause.png" Height="50" Width="70"/>
                    </td>
                    <td  >
                        <asp:ImageButton ID="dvdforward" runat="server"  ImageUrl="~/Images/button_forward (1).png" Height="50" Width="70" />
                    </td>
                </tr>
                 <tr>
                    <td >
                       <asp:ImageButton ID="dvdrewind" runat="server"  ImageUrl="~/Images/button_rewind.png" Height="50" Width="70"/>
                    </td>
                    
                </tr>
                
            </table>

        </asp:Panel>
    </div>
            
     </ContentTemplate>
           
        </asp:UpdatePanel>
        
    </div>
    
    

</asp:Content>

