<%@ Page Title="" Language="C#" MasterPageFile="~/MastersChild.master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="WebCresij.Dashboard" %>

<asp:Content ID="Content1" ContentPlaceHolderID="masterchildHead" runat="server">
    <link rel="stylesheet" href="lib/advanced-datatable/css/DT_bootstrap.css" />
    <link href="css/DropDownStyle.css" rel="stylesheet" />
    <link href="assets/css/charts.css" rel="stylesheet" />
    <link href="Content/Chart.min.css" rel="stylesheet" />
    <script src="Scripts/Chart.min.js"></script>
    <script src="Scripts/tablesorter/jquery.tablesorter.min.js"></script>
    <style>
        .portlet {
            clear: both;
            margin-top: 0px;
            margin-bottom: 25px;
            padding: 0px;
            -webkit-box-shadow1: 0 1px 4px rgba(0, 0, 0, 0.07);
            box-shadow1: 0 1px 4px rgba(0, 0, 0, 0.07);
            border: 1px solid #ddd;
            border-radius: 4px;
        }

            .portlet > .portlet-title {
                background-color: #eee;
                border-radius: 4px 4px 0 0;
                padding: 10px 10px 2px 10px;
                height: 38px;
            }

            .portlet > .portlet-body {
                clear: both;
                padding: 10px;
                background-color: #fff;
                border-radius: 0px 0px 4px 4px;
            }

        .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
            color: #555;
            cursor: default;
            background-color: #fff;
            border: 1px solid #ddd;
            border-bottom-color: transparent;
        }

        .nav-tabs > li > a {
            margin-right: 2px;
            line-height: 1.42857143;
            border: 1px solid transparent;
            border-radius: 4px 4px 0 0;
        }

        .nav > li > a {
            position: relative;
            display: block;
            padding: 10px 15px;
        }

        .scroller {
            position: relative;
            overflow: hidden;
            width: auto;
            height: 250px;
        }

        .btn-group-justified {
            display: table;
            width: 100%;
            table-layout: fixed;
            border-collapse: separate;
        }

        .carddata {
            margin-top: -15px;
            margin-left: -10px;
            font-size: 1.5rem!important;
        }

        @media screen and ( max-width: 1700px) and (min-width:1251px) {
            .carddata {
               
                
                font-size: 1.1rem!important;
            }
        }

        @media screen and ( max-width: 1250px) and (min-width:1190px) {
            .carddata {
              
                font-size: 1rem!important;
            }
        }

        .divstyle {
            background-color: #191b28;
            color: white;
            -moz-box-shadow: inset 0 0 15px #000000;
            -webkit-box-shadow: inset 0 0 15px #000000;
            box-shadow: inset 0 0 15px #000000;
            border-width: 2px 10px 10px 2px;
            margin-left: 15px;
            margin-right: 15px
        }

        gridviewclass > td {
            border: none !important;
        }

        gridviewclass > tr {
            border-bottom: 1px solid white !important;
        }

        gridviewclass > th {
            border: none !important
        }

        .gridPager table td {
            border: none !important;
        }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="masterchildBody" runat="server">
    <script src="Scripts/jquery.signalR-2.4.0.js"></script>
    <script src="Scripts/jquery.signalR-2.4.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script>
    <script src="Scripts/Dashboard.js"></script>
    <h3>Dashboard</h3>
    <div class="row">
        <div class=" col-xl-2 col-lg-4 col-md-6 col-sm-6">
            <div class="card" style="background-color: aqua; height: 120px;">
                <div class="card-body">
                    <div style="width: 70%; float: left;" class="carddata">
                        <span ><i class=" fa fa-users" aria-hidden="true"></i>&nbsp; Active users</span>
                    </div>
                    <div style="width: 20%; float: right">
                        <asp:Label runat="server" ID="userNo" Font-Size="24px"></asp:Label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-lg-4 col-md-6 col-sm-6">
            <div class="card" style="background-color: aqua; height: 120px;">
                <div class="card-body">
                    <div style="width: 80%; float: left;" class="carddata">
                        <span ><i class=" fa fa-users" aria-hidden="true"></i>&nbsp; Registered users</span>
                    </div>
                    <div style="width: 20%; float: right">
                        <asp:Label runat="server" ID="totalUser" Font-Size="24px"></asp:Label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-lg-4 col-md-6 col-sm-6">
            <div class="card" style="background-color: aqua; height: 120px;">
                <div class="card-body">
                    <div style="width: 70%; float: left;" class="carddata">
                        <span ><i class=" fa fa-cogs" aria-hidden="true"></i>&nbsp; Active Connections</span>
                    </div>
                    <div style="width: 20%; float: right">
                        <span id="TotalMachines" style="font-size: 24px"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-1 "></div>
        <div class="col-xl-6 col-lg-12 col-md-12 col-sm-12">
             <div class="divstyle" style=" margin-bottom:30px; ">
                
            <canvas id="myChart" height="370" ></canvas></div>
               
                 <div class="divstyle" >
                      <canvas id="pieChart" height="370"></canvas>
                 </div>
           
        </div>
        <div class="col-xl-6 col-lg-12 col-md-12 col-sm-12">
           
                 <div class="divstyle" style="min-height:520px">
                <h5>Activities</h5>
                <asp:UpdatePanel runat="server">
                    <ContentTemplate>
                        <div class="row" style="padding-right: 5px">
                            <div class="col">
                                <asp:DropDownList ID="ddlsort" runat="server" AutoPostBack="true"
                                    CssClass="btn btn-default border dropdown1" ForeColor="black"
                                    OnSelectedIndexChanged="Ddlsort_SelectedIndexChanged">
                                    <asp:ListItem Value="UserName" Text="User Name"></asp:ListItem>
                                    <asp:ListItem Value="Time" Text="<%$Resources:Resource, Time %>"></asp:ListItem>
                                    <asp:ListItem Value="Task" Text="Tasks"></asp:ListItem>
                                    <asp:ListItem Value="UserID" Text="UserID"></asp:ListItem>
                                </asp:DropDownList>
                                <asp:LinkButton runat="server" ID="btnAsc" CssClass="icons1" OnClick="BtnAsc_Click"
                                    Text='<i class="fa fa-sort-alpha-down"></i>'></asp:LinkButton>
                            </div>
                        </div>
                        <div style="padding-right: 10px;  ">

                            <asp:GridView runat="server" CellPadding="0" CellSpacing="0" ID="gv1" GridLines="None"
                                border="0" class="display table gridviewclass" AutoGenerateColumns="false"
                                AllowSorting="true" OnSorting="Gv1_Sorting"
                                AllowPaging="true" PageSize="10" PagerSettings-Mode="Numeric" ForeColor="White"
                                OnPageIndexChanging="Gv1_PageIndexChanging" PagerStyle-ForeColor="White">
                                <PagerStyle CssClass="gridPager" Font-Underline="true" />
                                <Columns>
                                    <asp:BoundField HeaderText="User ID" DataField="UserID" />
                                    <asp:BoundField HeaderText="User Name" DataField="UserName" />
                                    <asp:BoundField HeaderText="Tasks" DataField="Task" />
                                    <asp:BoundField HeaderText="Time" DataField="Time" />
                                </Columns>
                            </asp:GridView>
                        </div>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </div>
        </div>
      
    </div>
    <script type="text/javascript" src="lib/advanced-datatable/js/jquery.js"></script>
    <script type="text/javascript" src="lib/advanced-datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="lib/advanced-datatable/js/DT_bootstrap.js"></script>
    <script src="lib/common-scripts.js?v=4"></script>
</asp:Content>
