<%@ Page Title="" Language="C#" MasterPageFile="~/MastersChild.master" AutoEventWireup="true" CodeBehind="editDelCard.aspx.cs" Inherits="trythis.editDelCard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="masterchildHead" runat="server">
    <style type="text/css">
        .textdec{
            text-decoration:underline;
        }
    </style>
    <link href="lib/advanced-datatable/css/demo_page.css" rel="stylesheet" />
  <link href="lib/advanced-datatable/css/demo_table.css" rel="stylesheet" />
  <link rel="stylesheet" href="lib/advanced-datatable/css/DT_bootstrap.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="masterchildBody" runat="server">
    <div >
         <div class=" row mb">
                     <div class="content-panel ">
        <asp:UpdatePanel runat="server">
            <ContentTemplate>
        <table border="0" cellpadding="0" cellspacing="0" width="50%">
    <tr>
        <td><b>Name</b></td>
        <td><asp:TextBox ID="txtname" runat="server" /></td>
        <td><b>Location</b></td>
        <td><asp:TextBox ID="txtloc" runat="server" OnTextChanged="txtloc_TextChanged" /></td>
        <td><asp:Button ID="btnSearch" runat="server" Text="Search" 
                onclick="btnSearch_Click" /></td>
    </tr>
</table>
<br />
                
                <div class=" row mb">
                     
            <div class="adv-table">
<asp:GridView ID="gvCard" runat="server" AutoGenerateColumns="false" OnPageIndexChanging="gvCard_PageIndexChanging" 
    Width="95%" PageSize="10"  AllowPaging="true" class="display table table-bordered" 
    AutoGenerateEditButton="true" AutoGenerateDeleteButton="false"
     OnRowDeleting="gvCard_RowDeleting"
    AllowSorting="true" OnSorting="gvCard_Sorting" 
    DataKeyNames="CardID" 
     RowStyle-Height="60px" BorderStyle="None" 
    PagerSettings-Mode="Numeric" >
     <HeaderStyle CssClass="hidden-phone"  Height="60px" />
        <rowstyle CssClass="gradeX center" Height="60px"  />
        <alternatingrowstyle CssClass="gradeC center" Height="60px"  />
    
    <Columns>
        
        <asp:TemplateField HeaderText="Member ID" SortExpression="memberID">  
            <ItemStyle Width="8%" Height="50px" /><ControlStyle Width="100%" />
            <ItemTemplate>                
                <asp:Label runat="server" Text='<%#Eval("memberID") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Name" SortExpression="Name">
            <ItemStyle Width="8%" Height="50px" /><ControlStyle Width="100%" />
            <ItemTemplate>
                <asp:Label runat="server" Text='<%#Eval("Name") %>'></asp:Label>                
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField>
            <ItemStyle Width="10%"  Height="50px" /><ControlStyle Width="100%" />
            <ItemTemplate>
                <asp:Label ID="cardId" runat="server" Text='<%#Eval("CardID") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:BoundField HeaderText="Status"  
            DataField="State" ReadOnly="true" ItemStyle-Width="14%" ControlStyle-Width="100%" >
        </asp:BoundField>     
        
        <asp:TemplateField HeaderText="Access Granted(To)" SortExpression="locnames">
            <ItemStyle Width="25%" Height="50px"/><ControlStyle Width="100%" />
            <ItemTemplate>
                <asp:Label runat="server" Text='<%#Eval("locnames") %>'></asp:Label>               
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField>
            <ItemTemplate>
                <asp:Label Text='<%#Eval("locids") %>' Visible="false" runat="server" ID="hidlocID"></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
    
        <asp:TemplateField HeaderText="Pending Access(For)" SortExpression="pending">
            <ItemStyle Width="25%" Height="50px"/><ControlStyle Width="100%" />
            <ItemTemplate>
                <asp:Label runat="server" ID="lblPending" Text='<%#Eval("pending") %>'></asp:Label>               
            </ItemTemplate>
        </asp:TemplateField>  
        
        <asp:TemplateField HeaderText="Comments" >
            <ItemStyle Width="10%"  Height="50px" /><ControlStyle Width="100%" />
            <ItemTemplate>
                <asp:Label runat="server" Text='<%#Eval("Comment") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
         <asp:TemplateField>
        <ItemTemplate>
        <asp:LinkButton Runat="server" 
            OnClientClick="return confirm('Are you sure you want to delete this?');" 
            CommandName="Delete">Delete</asp:LinkButton>
        </ItemTemplate>

    </asp:TemplateField>
        <asp:TemplateField>
            <ItemTemplate>
                <asp:LinkButton runat="server" Text="Resend" ToolTip="Resend to Register" OnClick="Unnamed_Click" />
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
</asp:GridView>
                </div>
                         
                    </div>
           </ContentTemplate>
            
        </asp:UpdatePanel>
                         </div>
             </div>
    </div>
</asp:Content>

