<%@ Page Title="" Language="C#" MasterPageFile="~/MastersChild.master"
    AutoEventWireup="true" CodeBehind="editDelCard.aspx.cs" 
    Inherits="WebCresij.editDelCard" %>

<asp:Content ID="Content1" ContentPlaceHolderID="masterchildHead" runat="server">
    <style type="text/css">
        .textdec {
            text-decoration: underline;
        }
        .displaynone {
            display: none;
        }
    </style>
    <link href="lib/advanced-datatable/css/demo_page.css" rel="stylesheet" />
    <link href="lib/advanced-datatable/css/demo_table.css" rel="stylesheet" />
    <link rel="stylesheet" href="lib/advanced-datatable/css/DT_bootstrap.css" />
    <script src="Scripts/editCard.js?v=4"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="masterchildBody" runat="server">
    <div>
        <div class=" row mb" style="width: 100%">
            <asp:UpdatePanel runat="server">
                <ContentTemplate>
                    <div class="row mb">
                        <table border="0" cellpadding="0" cellspacing="0" width="50%">
                            <tr>
                                <td>
                                    <asp:TextBox ID="txtloc" runat="server" AutoPostBack="true"
                                        Width="70%" placeHolder="<%$Resources:Resource, Search %>"
                                        CssClass="form-control"
                                        OnTextChanged="txtloc_TextChanged" /></td>
                                <%--<span style="color:darkslategray"><i class="fa fa-search" 
                                        aria-hidden="true"></i></span>--%>
                            </tr>
                        </table>
                    </div>
                    <br />
                    <div class=" row mb adv-table">

                        <asp:GridView ID="gvCard" runat="server" 
                            AutoGenerateColumns="false"
                            OnPageIndexChanging="gvCard_PageIndexChanging"
                            PageSize="10" AllowPaging="true"
                            class="display table table-bordered"
                            AutoGenerateDeleteButton="false" 
                            AutoGenerateEditButton="true"
                            OnRowCancelingEdit="gvCard_RowCancelingEdit"
                            OnRowEditing="gvCard_RowEditing"
                            OnRowUpdating="gvCard_RowUpdating" 
                            AllowSorting="true" CellPadding="20" CellSpacing="20"
                            OnSorting="gvCard_Sorting" 
                            DataKeyNames="CardID"
                            BorderStyle="None" Width="100%" 
                            PagerSettings-Mode="Numeric">
                            <HeaderStyle CssClass="hidden-phone" HorizontalAlign="Center" 
                               BackColor="Transparent" ForeColor="white" />
                            <RowStyle HorizontalAlign="Center"  ForeColor="White" />
                            <%--<AlternatingRowStyle CssClass=" center" 
                                BackColor="WhiteSmoke" />--%>
                            <Columns>
                                <asp:BoundField SortExpression="memberID" 
                                    HeaderText="<%$Resources:Resource, MemberID %>"
                                    ItemStyle-Width="10%"
                                    DataField="memberID" ControlStyle-Width="100%" />
                                <asp:BoundField ItemStyle-Width="15%"
                                    HeaderText="<%$Resources:Resource, Name %>"
                                     SortExpression="Name"
                                    ControlStyle-Width="100%" DataField="memberName" />
                                <asp:BoundField SortExpression="CardID"
                                    HeaderText="<%$Resources:Resource, CardID %>"                                    
                                    ItemStyle-Width="10%" DataField="CardID"
                                    ReadOnly="true" ControlStyle-Width="100%" />
                                <asp:BoundField SortExpression="State" 
                                    DataField="State" ControlStyle-Width="100%"
                                    HeaderText="<%$Resources:Resource, Status %>"                                    
                                    ReadOnly="true" ItemStyle-Width="15%"/>
                                <asp:BoundField ReadOnly="true"
                                    HeaderText="<%$Resources:Resource, Accesspermitted %>"
                                    SortExpression="locnames" ItemStyle-Width="20%"
                                    DataField="locnames" ControlStyle-Width="100%"/>
                                <%--<asp:BoundField Visible="false" DataField="locids" />--%>
                                <asp:BoundField SortExpression="pending"
                                    HeaderText="<%$Resources:Resource, PendingAccess %>"
                                    ItemStyle-Width="15%" ReadOnly="true"
                                    ControlStyle-Width="100%" DataField="pending_loc" />
                                <asp:BoundField ItemStyle-Width="5%" 
                                    ControlStyle-Width="100%"
                                    HeaderText="<%$Resources:Resource, Comments %>"
                                    DataField="Comment" />
                                <asp:TemplateField Visible="false">
                                    <ControlStyle Width="100%" />
                                    <ItemTemplate>
                                        <asp:Label Text='<%#Eval("locationid") %>' 
                                            runat="server" ID="hidlocID">
                                        </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <controlstyle width="100%" />
                                        <asp:LinkButton runat="server" ForeColor="DeepSkyBlue"
                                            Text="<%$Resources:Resource, Resend %>"
                                            ToolTip="<%$Resources:Resource, toolTipResend%>"
                                            OnClick="Unnamed_Click" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField
                                    HeaderText="<%$Resources:Resource, ChangeLocation %>">
                                    <ItemStyle Width="10%" />
                                    <ControlStyle Width="100%" />
                                    <ItemTemplate>
                                        <asp:LinkButton ID="selectAccessTree" ForeColor="DeepSkyBlue"
                                            ToolTip="<%$Resources:Resource, ToolTipLocation %>"
                                            runat="server" OnClick="openaccess_Click"
                                            Text="<%$Resources:Resource, Select %>"
                                            CssClass="linkcursor"></asp:LinkButton>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>
        <div class="modal" id="modalAccess" style="max-height: 600px; 
        display: none; overflow-y: auto; position: center; 
            margin-left: 300px; margin-top: 200px">
            <div class="modal-content" style="width: 600px">
                <span class="close1" id="modalClose" style="text-align: right">
                    <i class="fa fa-times" aria-hidden="true"></i></span>
                <h3><span><%=Resources.Resource.SelectLocation%></span></h3>
                <asp:UpdatePanel runat="server" ID="selectAccessPanel">
                    <ContentTemplate>
                        <asp:TreeView ShowCheckBoxes="All" ID="TreeView1" 
                            NodeStyle-NodeSpacing="1" runat="server">
                        </asp:TreeView>
                  <%-- <button onclick="GetSelected()">select</button>--%>
                        <asp:Button Text="<%$Resources:Resource, GetSelected %>" 
                            runat="server" ID="btnToSelect" 
                            OnClick="addAccess_Click" ClientIDMode="Static" />
                    </ContentTemplate>
                </asp:UpdatePanel>
                <%--<input type="button" id=" btnselect" title="select"
                    value="select" />--%>
                <input id="hfSelected" type="hidden" runat="server" />
            </div>
        </div>
    </div>
</asp:Content>

