<%@ Page Title="" Language="C#" MasterPageFile="~/MastersChild.master" AutoEventWireup="true" CodeBehind="editDelCard.aspx.cs" Inherits="WebCresij.editDelCard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="masterchildHead" runat="server">
    <style type="text/css">
        .textdec{
            text-decoration:underline;
        }
        .displaynone{
            display:none;
        }
    </style>
    <link href="lib/advanced-datatable/css/demo_page.css" rel="stylesheet" />
  <link href="lib/advanced-datatable/css/demo_table.css" rel="stylesheet" />
  <link rel="stylesheet" href="lib/advanced-datatable/css/DT_bootstrap.css" />
    <script src="Scripts/editCard.js?v=3"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="masterchildBody" runat="server">
    <div>
         <div class=" row mb" style="width:100%">
         <div class="content-panel ">
         <asp:UpdatePanel runat="server">
            <ContentTemplate >
                <div class="row mb">
                    <table border="0" cellpadding="0" cellspacing="0" width="50%">
                        <tr>  
                            <td>
                            <asp:TextBox ID="txtloc" runat="server" AutoPostBack="true" Width="70%"
                            placeHolder="search" CssClass="form-control" OnTextChanged="txtloc_TextChanged" /></td>
       <%-- <span style="color:darkslategray"><i class="fa fa-search" aria-hidden="true"></i></span>--%>
                       </tr>
                    </table>
              </div>
              <br/>                
            <div class=" row mb">                    
            <div class="adv-table">
<asp:GridView ID="gvCard" runat="server" AutoGenerateColumns="false" 
        OnPageIndexChanging="gvCard_PageIndexChanging" 
     PageSize="10"  AllowPaging="true" class="display table table-bordered" 
     AutoGenerateDeleteButton="false" AutoGenerateEditButton="true"
     OnRowCancelingEdit="gvCard_RowCancelingEdit"
    OnRowEditing="gvCard_RowEditing" 
     OnRowUpdating="gvCard_RowUpdating" 
    AllowSorting="true" OnSorting="gvCard_Sorting" 
    DataKeyNames="CardID" 
      BorderStyle="None" Width="95%" 
    PagerSettings-Mode="Numeric" >
     <HeaderStyle CssClass="hidden-phone"  Height="60px" />
        <rowstyle CssClass="gradeX center" Height="60px"  />
        <alternatingrowstyle CssClass="gradeC center" Height="60px"  />
    <Columns>
       <asp:BoundField HeaderText="MemberID" SortExpression="memberID" ItemStyle-Width="10%" DataField="memberID" ControlStyle-Width="100%"  />     
        <asp:BoundField HeaderText="Name" ItemStyle-Width="15%" SortExpression="Name" ControlStyle-Width="100%" DataField="Name" />
        <asp:BoundField HeaderText="Card ID" SortExpression="CardID"
             ItemStyle-Width="10%" DataField="CardID" ReadOnly="true" ControlStyle-Width="100%" />       
        <asp:BoundField HeaderText="Status" SortExpression="State"  
            DataField="State" ReadOnly="true" ItemStyle-Width="15%"  ControlStyle-Width="100%" >
        </asp:BoundField>     
        <asp:BoundField HeaderText="Access Granted(To)" SortExpression="locnames"
            ItemStyle-Width="20%" DataField="locnames" ControlStyle-Width="100%" ReadOnly="true" />
        <%--<asp:BoundField Visible="false" DataField="locids" />--%>     
        <asp:BoundField HeaderText="Pending Access(For)" SortExpression="pending"        
        ItemStyle-Width="20%" ReadOnly="true" ControlStyle-Width="100%" DataField="pending" />     
        <asp:BoundField ItemStyle-Width="10%" ControlStyle-Width="100%" HeaderText="Comments" DataField="Comment" />      
        <%-- <asp:TemplateField>
             <ControlStyle Width="100%" />
        <ItemTemplate>
        <asp:LinkButton Runat="server" 
            OnClientClick="return confirm('Are you sure you want to delete this?');" 
            CommandName="Delete">Delete</asp:LinkButton>
        </ItemTemplate>               
        </asp:TemplateField>--%>
         <asp:TemplateField Visible="false">
             <ControlStyle Width="100%" />
            <ItemTemplate>
                <asp:Label Text='<%#Eval("locids") %>' runat="server" ID="hidlocID"></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField>
            <ItemTemplate>
                <ControlStyle Width="100%" />
                <asp:LinkButton runat="server" Text="Resend" ToolTip="Resend to Register" OnClick="Unnamed_Click" />
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Change Location">
            <ItemStyle width="10%"/>
                <ControlStyle Width="100%" />
                 <ItemTemplate>
                     <asp:LinkButton ID="selectAccessTree" ToolTip="Click to change location access"
                         runat="server" text="select" CssClass="linkcursor"
                         OnClientClick="openTreeModal(); return false;"
                         OnClick="openaccess_Click"></asp:LinkButton>
            </ItemTemplate>
       </asp:TemplateField>
    </Columns>
</asp:GridView>
                </div>
            </div>
           </ContentTemplate>
        </asp:UpdatePanel>
        </div>
       </div>
       <div class="modal" id="modalAccess" style="max-height:600px; display:none;
        overflow-y:auto; position:center; margin-left:300px; margin-top:200px">
            <div class="modal-content" style="width:600px">
                 <span class="close1" id="modalClose" style="text-align:right">
                     <i class="fa fa-times" aria-hidden="true"></i></span>
                     <h3> Select Locations</h3>
                     <asp:UpdatePanel runat="server" ID="selectAccessPanel">
                     <ContentTemplate>
                     <asp:TreeView  ShowCheckBoxes="All" ID="TreeView1" NodeStyle-NodeSpacing="1"
                         runat="server"></asp:TreeView>
                                   <%-- <button onclick="GetSelected()">select</button>--%>
                     <asp:Button Text="Get Selected" runat="server" ID="btnToSelect"  OnClick="addAccess_Click"/>
                     </ContentTemplate>
                     </asp:UpdatePanel>
                     <%--<input type="button" id=" btnselect" title="select" value="select" />--%>
                     <input id="hfSelected" type="hidden" runat="server" />
            </div>                           
      </div>
    </div>         
</asp:Content>

