<%@ Page Title="" Language="C#" MasterPageFile="~/MastersChild.Master" 
    AutoEventWireup="true" CodeBehind="Status.aspx.cs" Inherits="WebCresij.Status" %>

<%@ MasterType VirtualPath="~/Master.master" %>
<asp:Content ID="Head" ContentPlaceHolderID="masterchildHead" runat="server">
    <style type="text/css">
        .imgclick {
            height: 40px;
            width: 40px;         
        }
            .imgclick:active {
                height: 42px;
                width: 42px;
            }
            .imgclick:hover {
                -webkit-border-radius: 15px;
                -moz-border-radius: 15px;
                border-radius: 15px;
                -webkit-box-shadow: 0px 0px 30px 0px rgba(37,155,51, 0.67);
                -moz-box-shadow: 0px 0px 30px 0px rgba(37,155,51, 0.67);
                box-shadow: 0px 0px 30px 0px rgba(37,155,51, 0.67);
            }
            .cssPager span { font-size:x-large; text-decoration-line:underline} 
            .cssPager td{
                padding-left:4px ;
                padding-right:4px;
            }
    </style>
    <%--</asp:Content>--%>
</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="masterchildBody" runat="server">    
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.1.js"></script>
    <script src="Scripts/jquery.signalR-2.4.1.min.js"></script>
    
    <!--Reference the autogenerated SignalR hub script. -->
    <script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script>
    <script src="Scripts/MessagesToClient.js?v=8" type="text/javascript"></script>
    <div class="row" style="padding-right: 15px; ">
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <table style="width: 95%; margin-top:-40px;" >
                    <tr  style="height: 50px; width:100%;padding-bottom:10px">
                        <td style="text-align: Left; color:white">&nbsp;
                            <h3 style="text-decoration:underline"><%=Resources.Resource.Status%></h3></td>
                        <td style="display: flex; justify-content: flex-end;">
                            <span style="float: right; color: white;   padding-top:15px">
                                <%--<i class="fa fa-refresh fa-3x" id="refresh"></i>--%>
                                <img src="Images/refresh.png" id="refresh" class="imgclick" />
                            </span>
                        </td>
                    </tr>
                    <tr style="padding-bottom:10px">
                        <td style="width: 50%" colspan="2">
                            <br />
                            <label for="ddlins" style="color:white; font-size:large">&nbsp;<span style="padding-right:10px">
                                <%=Resources.Resource.SelectInstitute%></span></label>
                            <asp:DropDownList ID="ddlins" runat="server" AutoPostBack="true"  Width="150px"
                                OnSelectedIndexChanged="ddlins_SelectedIndexChanged" ForeColor="White" 
                                CssClass="btn btn-default border dropdown" BackColor="#1E1E36">
                            </asp:DropDownList>
                        &nbsp;&nbsp;&nbsp;
                            <label for="ddlins" style="color:white; font-size:large">&nbsp;<span style="padding-right:10px">
                                <%=Resources.Resource.SelectGrade%></span></label>
                            <asp:DropDownList Width="100px" ID="ddlGrade" AutoPostBack="true"
                            CssClass="btn btn-default border dropdown"
                            OnSelectedIndexChanged="ddlGrade_SelectedIndexChanged"
                            runat="server"
                            ForeColor="White" BackColor="#1E1E36">
                            <asp:ListItem Text="<%$Resources:Resource, Select %>"
                                Value="NA"></asp:ListItem>  
                        </asp:DropDownList>
                            <%--&nbsp;&nbsp;&nbsp;
                            <label for="ddlins" style="color:white; font-size:large">&nbsp;<span style="padding-right:10px">
                                State</span></label>
                            <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="true"  Width="100px"
                                OnSelectedIndexChanged="ddlins_SelectedIndexChanged"
                                CssClass="btn btn-default border dropdown"  ForeColor="White" BackColor="#1E1E36">
                                <asp:ListItem Text="On" Value="On"></asp:ListItem>
                                <asp:ListItem Text="Off" Value="Off"></asp:ListItem>
                            </asp:DropDownList>--%>
                            
                        </td>
                    </tr>
                     <tr  style="padding-bottom:10px">
                        <td  style=" width: 50%;color:white" colspan="2">
                            <asp:UpdatePanel runat="server">
                                <ContentTemplate>
                                    <span><%=Resources.Resource.SystemOnline %>: <span  id="labelonline">0</span> </span>
                                                              
                            &nbsp;&nbsp;&nbsp;
                                    <span ><%=Resources.Resource.SystemOffline %>: <span id="labeloffline">0</span></span>
                           
                            &nbsp;&nbsp;&nbsp;
                                    <span ><%=Resources.Resource.SystemOn %>: <span id="labelstatuson">0</span></span>
                                                       
                            &nbsp;&nbsp;&nbsp;
                                    <span ><%=Resources.Resource.SystemOff %>: <span id="labelstatusoff">0</span></span>
                            
                                </ContentTemplate>
                            </asp:UpdatePanel>
                            
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="width: 100%; min-width:400px">
                            <asp:GridView ID="GridView1" runat="server" Font-Size="Small" ViewStateMode="Enabled"
                                EmptyDataRowStyle-BackColor="Black" AllowPaging="true" PageSize="12"
                                 OnPageIndexChanging="GridView1_PageIndexChanging" PagerSettings-Mode="NumericFirstLast" 
                                 PagerStyle-ForeColor="White" AllowSorting="true"  
                                ShowHeaderWhenEmpty="true" RowStyle-HorizontalAlign="Center"
                                EmptyDataRowStyle-ForeColor="White" AutoGenerateColumns="false">
                                <HeaderStyle Font-Bold="True" ForeColor="white" HorizontalAlign="Center"
                                    CssClass="table table-striped table-bordered table-hover" />
                                <RowStyle CssClass="iprows" BackColor="WhiteSmoke" ForeColor="black" Height="38" />
                                <AlternatingRowStyle CssClass="iprows" BackColor="White" ForeColor="black" Height="38" />
                                <PagerStyle CssClass="cssPager" Font-Size="Large" HorizontalAlign="Center"
                                     Height="20px"/>
                                <Columns>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, Grade %>" 
                                        DataField="Grade">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%"></ControlStyle>
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, ClassName %>" 
                                        DataField="loc">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%"></ControlStyle>
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, IPAddress %>" 
                                        DataField="CCIP">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, Status %>" 
                                        DataField="Status">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, WorkStatus %>" 
                                        DataField="PowerStatus">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, TimerService %>" 
                                        DataField="TimerService">
                                        <ItemStyle Width="4%" />
                                        <ControlStyle Width="4%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, PCPower %>" 
                                        DataField="ComputerPower">
                                        <ItemStyle Width="4%" />
                                        <ControlStyle Width="4%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, ProjectorPower %>" 
                                        DataField="ProjectorPower">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, ProjectorHours %>" 
                                        DataField="ProjectorUsedHour">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, CurtainStatus %>"
                                        DataField="CurtainStatus">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, SCStatus %>"
                                        DataField="ScreenStatus">
                                        <ItemStyle Width="6%" />
                                        <ControlStyle Width="6%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, Light%>"
                                        DataField="light">
                                        <ItemStyle Width="4%" />
                                        <ControlStyle Width="4%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, MediaSignal %>"
                                        DataField="MediaSignal">
                                        <ItemStyle Width="10%" />
                                        <ControlStyle Width="10%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, SystemLock %>"
                                        DataField="centrallock">
                                        <ItemStyle Width="5%" />
                                        <ControlStyle Width="5%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, PodiumLock %>"
                                        DataField="podiumLock">
                                        <ItemStyle Width="5%" />
                                        <ControlStyle Width="5%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, ClassLock %>"
                                        DataField="ClassLock">
                                        <ItemStyle Width="5%" />
                                        <ControlStyle Width="5%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, Temperature %>"
                                        DataField="temperature">
                                        <ItemStyle Width="4%" />
                                        <ControlStyle Width="4%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="<%$Resources:Resource, Humidity %>"
                                        DataField="humidity">
                                        <ItemStyle Width="4%" />
                                        <ControlStyle Width="4%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="PM2.5(µg/m3)" DataField="pm25">
                                        <ItemStyle Width="4%" />
                                        <ControlStyle Width="4%" />
                                    </asp:BoundField>
                                    <asp:BoundField HeaderText="PM10(µg/m3)" DataField="pm10">
                                        <ItemStyle Width="4%" />
                                        <ControlStyle Width="4%" />
                                    </asp:BoundField>
                                </Columns>
                            </asp:GridView>
                        </td>
                    </tr>
                </table>
            </ContentTemplate>
        </asp:UpdatePanel>
        <input type="hidden" value="0" id="pageindex"/>
    </div>
   <%--<asp:Timer ID="Timer1" runat="server"></asp:Timer>--%>
</asp:Content>
<%--</asp:Content>--%>


<%--  <div class=" row site-footer" style=" padding-right:20px; " >
                        <div class="panel-heading col-md-8" >
                             Status:
                        </div>
                        <div class="col-md-4" style="display:flex; justify-content:flex-end; ">
                            <%--<input type="image" src="Images/refresh.png"  id=" refresh" 
    height="40" width="40" />
                            
                         <a id="refresh" href="#" style="float:right; color:white;">
                             <image src="Images/refresh.png" height="40" width="40" alt="Refresh"></image>
                         </a>
                   </div>
                        </div>--%>

                        
       
