//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseEntities : DbContext
    {
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buildingdetail> buildingdetails { get; set; }
        public virtual DbSet<classdetail> classdetails { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<current_loggeduser> current_loggeduser { get; set; }
        public virtual DbSet<departmentdetail> departmentdetails { get; set; }
        public virtual DbSet<floordetail> floordetails { get; set; }
        public virtual DbSet<operationmgmt> operationmgmts { get; set; }
        public virtual DbSet<reserveandtransfer> reserveandtransfers { get; set; }
        public virtual DbSet<roledetail> roledetails { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<scheduleoriginal> scheduleoriginals { get; set; }
        public virtual DbSet<schedulereserve> schedulereserves { get; set; }
        public virtual DbSet<scheduletransfer> scheduletransfers { get; set; }
        public virtual DbSet<sectionsinfo> sectionsinfoes { get; set; }
        public virtual DbSet<semesterinfo> semesterinfoes { get; set; }
        public virtual DbSet<strategyservicesandfeature> strategyservicesandfeatures { get; set; }
        public virtual DbSet<studentdata> studentdatas { get; set; }
        public virtual DbSet<systemsetting> systemsettings { get; set; }
        public virtual DbSet<teacheraidequipment> teacheraidequipments { get; set; }
        public virtual DbSet<teacherdata> teacherdatas { get; set; }
        public virtual DbSet<temp_centralcontrol> temp_centralcontrol { get; set; }
        public virtual DbSet<userdetail> userdetails { get; set; }
        public virtual DbSet<userlocationaccess> userlocationaccesses { get; set; }
        public virtual DbSet<userlog> userlogs { get; set; }
        public virtual DbSet<userpermission> userpermissions { get; set; }
        public virtual DbSet<userregistration> userregistrations { get; set; }
        public virtual DbSet<doc_info> doc_info { get; set; }
        public virtual DbSet<resultday> resultdays { get; set; }
        public virtual DbSet<resultschedule> resultschedules { get; set; }
        public virtual DbSet<resultschedulefrtransfer> resultschedulefrtransfers { get; set; }
        public virtual DbSet<resulttransferschedule> resulttransferschedules { get; set; }
        public virtual DbSet<view_getscheduletransfer> view_getscheduletransfer { get; set; }
        public virtual DbSet<view_resultschedule> view_resultschedule { get; set; }
        public virtual DbSet<view_resultschedule1> view_resultschedule1 { get; set; }
        public virtual DbSet<view_resultscheduledayweek> view_resultscheduledayweek { get; set; }
        public virtual DbSet<view_resultscheduledayweeksem> view_resultscheduledayweeksem { get; set; }
        public virtual DbSet<view_resultscheduledayweeksem1> view_resultscheduledayweeksem1 { get; set; }
        public virtual DbSet<view_resultscheduletransfer> view_resultscheduletransfer { get; set; }
        public virtual DbSet<view_resultscheduletransfer1> view_resultscheduletransfer1 { get; set; }
        public virtual DbSet<view_resulttestschedule> view_resulttestschedule { get; set; }
        public virtual DbSet<view_scheduletemporarytable> view_scheduletemporarytable { get; set; }
    }
}
