//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class classdetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classdetail()
        {
            this.schedulereserves = new HashSet<schedulereserve>();
            this.scheduletransfers = new HashSet<scheduletransfer>();
            this.temp_desktopevents = new HashSet<temp_desktopevents>();
            this.alarmmonitorlogs = new HashSet<alarmmonitorlog>();
        }
    
        public int classID { get; set; }
        public string ClassName { get; set; }
        public int teachingBuilding { get; set; }
        public int floor { get; set; }
        public int Seats { get; set; }
        public string camipS { get; set; }
        public string camipT { get; set; }
        public string camSmac { get; set; }
        public string camTmac { get; set; }
        public int camport { get; set; }
        public string camuserid { get; set; }
        public string campass { get; set; }
        public string CCEquipIP { get; set; }
        public string ccmac { get; set; }
        public string desktopip { get; set; }
        public string deskmac { get; set; }
        public string recordingEquip { get; set; }
        public string recordermac { get; set; }
        public string callhelpip { get; set; }
        public string callhelpmac { get; set; }
    
        public virtual buildingdetail buildingdetail { get; set; }
        public virtual floordetail floordetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedulereserve> schedulereserves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scheduletransfer> scheduletransfers { get; set; }
        public virtual temp_machinestatus temp_machinestatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temp_desktopevents> temp_desktopevents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alarmmonitorlog> alarmmonitorlogs { get; set; }
    }
}
