//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class floordetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public floordetail()
        {
            this.classdetails = new HashSet<classdetail>();
        }
    
        public int id { get; set; }
        public string floor { get; set; }
        public int BuildingName { get; set; }
        public string buildingcode { get; set; }
        public string Queue { get; set; }
        public string Public { get; set; }
        public string Remarks { get; set; }
    
        public virtual buildingdetail buildingdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classdetail> classdetails { get; set; }
    }
}
