//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_machineusagelogs
    {
        public int id { get; set; }
        public string Attribute { get; set; }
        public int classid { get; set; }
        public System.DateTime TimeRange { get; set; }
        public long attrvalue { get; set; }
    }
}
