//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class machineoperationlog
    {
        public int id { get; set; }
        public string Operation { get; set; }
        public System.DateTime ExecutionTime { get; set; }
        public int Location { get; set; }
        public string Type { get; set; }
    }
}
