//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganisationdatabaseEntities : DbContext
    {
        public OrganisationdatabaseEntities()
            : base("name=OrganisationdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buildingdetail> buildingdetails { get; set; }
        public virtual DbSet<classdetail> classdetails { get; set; }
        public virtual DbSet<departmentdetail> departmentdetails { get; set; }
        public virtual DbSet<floordetail> floordetails { get; set; }
        public virtual DbSet<operationmgmt> operationmgmts { get; set; }
        public virtual DbSet<reserveandtransfer> reserveandtransfers { get; set; }
        public virtual DbSet<roledetail> roledetails { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<scheduleoriginal> scheduleoriginals { get; set; }
        public virtual DbSet<schedulereserve> schedulereserves { get; set; }
        public virtual DbSet<scheduletransfer> scheduletransfers { get; set; }
        public virtual DbSet<sectionsinfo> sectionsinfoes { get; set; }
        public virtual DbSet<semesterinfo> semesterinfoes { get; set; }
        public virtual DbSet<strategydescription> strategydescriptions { get; set; }
        public virtual DbSet<strategyequipment> strategyequipments { get; set; }
        public virtual DbSet<strategylog> strategylogs { get; set; }
        public virtual DbSet<strategymanagement> strategymanagements { get; set; }
        public virtual DbSet<studentdata> studentdatas { get; set; }
        public virtual DbSet<systemsetting> systemsettings { get; set; }
        public virtual DbSet<teacherdata> teacherdatas { get; set; }
        public virtual DbSet<temp_centralcontrol> temp_centralcontrol { get; set; }
        public virtual DbSet<userdetail> userdetails { get; set; }
        public virtual DbSet<userlocationaccess> userlocationaccesses { get; set; }
        public virtual DbSet<userlog> userlogs { get; set; }
        public virtual DbSet<userpermission> userpermissions { get; set; }
        public virtual DbSet<userregistration> userregistrations { get; set; }
        public virtual DbSet<usersessioninfo> usersessioninfoes { get; set; }
        public virtual DbSet<machineoperationlog> machineoperationlogs { get; set; }
    }
}
