//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectorconfiginfo
    {
        public long configid { get; set; }
        public int Classid { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public int Baudrate { get; set; }
        public short parity { get; set; }
        public string OpenCode { get; set; }
        public string CloseCode { get; set; }
        public string status { get; set; }
    
        public virtual classdetail classdetail { get; set; }
    }
}
