//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserveandtransfer
    {
        public string Type { get; set; }
        public sbyte NonWorkingDays { get; set; }
        public sbyte AutoReview { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int SemesterNo { get; set; }
        public int id { get; set; }
    
        public virtual semesterinfo semesterinfo { get; set; }
    }
}
