//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedulereserve
    {
        public string SchoolYear { get; set; }
        public string Semester { get; set; }
        public string week { get; set; }
        public string Date { get; set; }
        public int Section { get; set; }
        public int Classroom { get; set; }
        public string BorrowingUnit { get; set; }
        public string Workphone { get; set; }
        public string PersonName { get; set; }
        public string PersonID { get; set; }
        public string ContactNo { get; set; }
        public string Purpose { get; set; }
        public string Reason { get; set; }
        public string ReservationDevices { get; set; }
        public string Status { get; set; }
        public int id { get; set; }
    
        public virtual classdetail classdetail { get; set; }
    }
}
