//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategyservicesandfeature
    {
        public int StrategyId { get; set; }
        public string StrategyName { get; set; }
        public string StrategyDescription { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Timeframe { get; set; }
        public string teacherAidEquipments { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string StrategyType { get; set; }
    }
}
