//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategylog
    {
        public int Id { get; set; }
        public int MachineMac { get; set; }
        public string Instruction { get; set; }
        public System.DateTime ExecutionTime { get; set; }
        public int StrategyDescId { get; set; }
        public string Status { get; set; }
        public int EquipmentId { get; set; }
    
        public virtual strategymanagement strategymanagement { get; set; }
    }
}
