//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentdata
    {
        public string studentid { get; set; }
        public string studentname { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string deptcode { get; set; }
        public string phone { get; set; }
        public string idcard { get; set; }
        public string onecard { get; set; }
    }
}
