//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemsetting
    {
        public string SchoolName { get; set; }
        public string SchoolEngName { get; set; }
        public string LogoLocation { get; set; }
        public int Id { get; set; }
    }
}
