//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_centralcontrol
    {
        public string ip { get; set; }
        public int loc { get; set; }
        public string status { get; set; }
        public string workstatus { get; set; }
        public string Timer { get; set; }
        public string pcstatus { get; set; }
        public string projectorstatus { get; set; }
        public string ProjHour { get; set; }
        public string curtain { get; set; }
        public string screen { get; set; }
        public string light { get; set; }
        public string mediasignal { get; set; }
        public string centrallock { get; set; }
        public string podiumlock { get; set; }
        public string classlock { get; set; }
        public string temperature { get; set; }
        public string humidity { get; set; }
        public string pm25 { get; set; }
        public string pm10 { get; set; }
    }
}
