//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersessioninfo
    {
        public string LoginID { get; set; }
        public string SessionId { get; set; }
        public System.DateTime SessionStartTime { get; set; }
        public int id { get; set; }
        public string SocketConnectionID { get; set; }
        public Nullable<System.DateTime> SessionEndTime { get; set; }
    }
}
