//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userregistration
    {
        public string UserName { get; set; }
        public string Userid { get; set; }
        public string userpassword { get; set; }
        public int Departmentid { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string UserType { get; set; }
    }
}
