//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CresijApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userpermission
    {
        public int userserialnum { get; set; }
        public int roleid { get; set; }
        public int id { get; set; }
        public int AuthenticatedBy { get; set; }
    
        public virtual roledetail roledetail { get; set; }
        public virtual userdetail userdetail { get; set; }
        public virtual userdetail userdetail1 { get; set; }
    }
}
