//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Control System.
        /// </summary>
        internal static string AC {
            get {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Permitted to.
        /// </summary>
        internal static string AccessPermitted {
            get {
                return ResourceManager.GetString("AccessPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Camera Details.
        /// </summary>
        internal static string AddCam {
            get {
                return ResourceManager.GetString("AddCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Card.
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Class.
        /// </summary>
        internal static string AddClass {
            get {
                return ResourceManager.GetString("AddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Devices.
        /// </summary>
        internal static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device Details.
        /// </summary>
        internal static string AddDeviceDetails {
            get {
                return ResourceManager.GetString("AddDeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Grades.
        /// </summary>
        internal static string AddGrades {
            get {
                return ResourceManager.GetString("AddGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Institutes And Grades.
        /// </summary>
        internal static string AddInsgrade {
            get {
                return ResourceManager.GetString("AddInsgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Successfully Added!!.
        /// </summary>
        internal static string AddInsSuccess {
            get {
                return ResourceManager.GetString("AddInsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Institutes.
        /// </summary>
        internal static string AddInstitutes {
            get {
                return ResourceManager.GetString("AddInstitutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Grades.
        /// </summary>
        internal static string AddNewgrade {
            get {
                return ResourceManager.GetString("AddNewgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        internal static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new User..!.
        /// </summary>
        internal static string AddNewUser1 {
            get {
                return ResourceManager.GetString("AddNewUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator(Full Access).
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check status of card !!.
        /// </summary>
        internal static string AlertCardStatus {
            get {
                return ResourceManager.GetString("AlertCardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be deleted!! Please expand more to delete devices!!.
        /// </summary>
        internal static string AlertDelete {
            get {
                return ResourceManager.GetString("AlertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details saved successfully!.
        /// </summary>
        internal static string AlertDeviceSuccess {
            get {
                return ResourceManager.GetString("AlertDeviceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Ip Can not be edited!! Please add a new device\n and delete the current device to make the changes.
        /// </summary>
        internal static string AlertEditIP {
            get {
                return ResourceManager.GetString("AlertEditIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit this!! Please expand more to edit devices!!.
        /// </summary>
        internal static string AlertEditNot {
            get {
                return ResourceManager.GetString("AlertEditNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS!! Something went wrong. Please try again!!.
        /// </summary>
        internal static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured!! Please try again!!.
        /// </summary>
        internal static string AlertError1 {
            get {
                return ResourceManager.GetString("AlertError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid number!.
        /// </summary>
        internal static string AlertError2 {
            get {
                return ResourceManager.GetString("AlertError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not have more than 1 IP address same in an Institute!!\n Please insert different IP(s)!!.
        /// </summary>
        internal static string AlertErrorIP {
            get {
                return ResourceManager.GetString("AlertErrorIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter different Member IDs Values!!.
        /// </summary>
        internal static string AlertMemberID {
            get {
                return ResourceManager.GetString("AlertMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name can contain letters, dot, hyphen and underscore only.
        /// </summary>
        internal static string AlertNameFormat {
            get {
                return ResourceManager.GetString("AlertNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter different Serial Number Values!!.
        /// </summary>
        internal static string AlertSerialNumber {
            get {
                return ResourceManager.GetString("AlertSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time and End Time should be different !!.
        /// </summary>
        internal static string AlertTime {
            get {
                return ResourceManager.GetString("AlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert time in right format\n Correct Format Should be for example - &apos;00:00-00:00&apos;.
        /// </summary>
        internal static string AlertTime2 {
            get {
                return ResourceManager.GetString("AlertTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Saved Successfully!!.
        /// </summary>
        internal static string AlertTime3 {
            get {
                return ResourceManager.GetString("AlertTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct time!!\n Time is in 24 hour Format!! Start time should be earlier than stop time!!\n eg. - 22:00 - 23:59.
        /// </summary>
        internal static string AlertTime4 {
            get {
                return ResourceManager.GetString("AlertTime4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Schedule data in excel file is not in required format.\n Please create excel file as below table format!!&quot;.
        /// </summary>
        internal static string AlertTime5 {
            get {
                return ResourceManager.GetString("AlertTime5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert data in excel without leave initial row(s)and column(s)!!.
        /// </summary>
        internal static string AlertTime6 {
            get {
                return ResourceManager.GetString("AlertTime6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot authorize user without providing any role!!.
        /// </summary>
        internal static string ApproveError {
            get {
                return ResourceManager.GetString("ApproveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate Users.
        /// </summary>
        internal static string AuthenticateUsers {
            get {
                return ResourceManager.GetString("AuthenticateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize user by Selecting Roles.
        /// </summary>
        internal static string AuthorizeUser {
            get {
                return ResourceManager.GetString("AuthorizeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize User..!.
        /// </summary>
        internal static string AuthUser {
            get {
                return ResourceManager.GetString("AuthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Off.
        /// </summary>
        internal static string AutoOff {
            get {
                return ResourceManager.GetString("AutoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto On.
        /// </summary>
        internal static string AutoOn {
            get {
                return ResourceManager.GetString("AutoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Recording.
        /// </summary>
        internal static string AutoRecord {
            get {
                return ResourceManager.GetString("AutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic White Balance.
        /// </summary>
        internal static string AutoWhiteBalance {
            get {
                return ResourceManager.GetString("AutoWhiteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baudrate and Parity.
        /// </summary>
        internal static string BaudParity {
            get {
                return ResourceManager.GetString("BaudParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaudRate.
        /// </summary>
        internal static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera IP.
        /// </summary>
        internal static string CamIP {
            get {
                return ResourceManager.GetString("CamIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardID.
        /// </summary>
        internal static string CardID {
            get {
                return ResourceManager.GetString("CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Logs.
        /// </summary>
        internal static string CardLogs {
            get {
                return ResourceManager.GetString("CardLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Registration.
        /// </summary>
        internal static string CardRegistration {
            get {
                return ResourceManager.GetString("CardRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Successfully Registered!.
        /// </summary>
        internal static string CardSuccessRegister {
            get {
                return ResourceManager.GetString("CardSuccessRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Control System IP Address.
        /// </summary>
        internal static string CCIPAddress {
            get {
                return ResourceManager.GetString("CCIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Location.
        /// </summary>
        internal static string ChangeLocation {
            get {
                return ResourceManager.GetString("ChangeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Lock Status.
        /// </summary>
        internal static string ClassLock {
            get {
                return ResourceManager.GetString("ClassLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 Level.
        /// </summary>
        internal static string CO2 {
            get {
                return ResourceManager.GetString("CO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电脑自动刚开机.
        /// </summary>
        internal static string CompAutoBoot {
            get {
                return ResourceManager.GetString("CompAutoBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电脑自动关机.
        /// </summary>
        internal static string CompAutoShut {
            get {
                return ResourceManager.GetString("CompAutoShut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电脑联动系统关.
        /// </summary>
        internal static string CompLinkageOff {
            get {
                return ResourceManager.GetString("CompLinkageOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Settings.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Settings.
        /// </summary>
        internal static string ConfigSettings {
            get {
                return ResourceManager.GetString("ConfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select options to create Schedule.
        /// </summary>
        internal static string CreateSchedule {
            get {
                return ResourceManager.GetString("CreateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain.
        /// </summary>
        internal static string Curtain {
            get {
                return ResourceManager.GetString("Curtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幕布联动投影机开.
        /// </summary>
        internal static string CurtainLinkage {
            get {
                return ResourceManager.GetString("CurtainLinkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain Status.
        /// </summary>
        internal static string CurtainStatus {
            get {
                return ResourceManager.GetString("CurtainStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Boot.
        /// </summary>
        internal static string DelayBoot {
            get {
                return ResourceManager.GetString("DelayBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete!!.
        /// </summary>
        internal static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Details.
        /// </summary>
        internal static string DeleteDetails {
            get {
                return ResourceManager.GetString("DeleteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Devices Details.
        /// </summary>
        internal static string DeleteDevice {
            get {
                return ResourceManager.GetString("DeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Documents.
        /// </summary>
        internal static string DeleteDocument {
            get {
                return ResourceManager.GetString("DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Files.
        /// </summary>
        internal static string DeleteFiles {
            get {
                return ResourceManager.GetString("DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Successfully Deleted !.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices Management.
        /// </summary>
        internal static string DeviceManagement {
            get {
                return ResourceManager.GetString("DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices Status.
        /// </summary>
        internal static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {0} to {1} of {2} records found.
        /// </summary>
        internal static string DisplayRecords {
            get {
                return ResourceManager.GetString("DisplayRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Deletion.
        /// </summary>
        internal static string DocDelete {
            get {
                return ResourceManager.GetString("DocDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string DocumentMenu {
            get {
                return ResourceManager.GetString("DocumentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document upload &amp; Download.
        /// </summary>
        internal static string DocUploadDownload {
            get {
                return ResourceManager.GetString("DocUploadDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Documents.
        /// </summary>
        internal static string DownloadDocument {
            get {
                return ResourceManager.GetString("DownloadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Files.
        /// </summary>
        internal static string DownloadFiles {
            get {
                return ResourceManager.GetString("DownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Boot.
        /// </summary>
        internal static string EarlyBoot {
            get {
                return ResourceManager.GetString("EarlyBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Camera Details !.
        /// </summary>
        internal static string EditCamDetails {
            get {
                return ResourceManager.GetString("EditCamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card Details.
        /// </summary>
        internal static string EditCard {
            get {
                return ResourceManager.GetString("EditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Details.
        /// </summary>
        internal static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device Details.
        /// </summary>
        internal static string EditDevice {
            get {
                return ResourceManager.GetString("EditDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Name.
        /// </summary>
        internal static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, Authenticate and Delete Users.
        /// </summary>
        internal static string EditUsers {
            get {
                return ResourceManager.GetString("EditUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        internal static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even.
        /// </summary>
        internal static string Even {
            get {
                return ResourceManager.GetString("Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Status.
        /// </summary>
        internal static string EvsStatus {
            get {
                return ResourceManager.GetString("EvsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Names.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹关.
        /// </summary>
        internal static string FingerPrintClose {
            get {
                return ResourceManager.GetString("FingerPrintClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹开.
        /// </summary>
        internal static string FingerPrintOpen {
            get {
                return ResourceManager.GetString("FingerPrintOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Air System.
        /// </summary>
        internal static string FreshAirSystem {
            get {
                return ResourceManager.GetString("FreshAirSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Selected.
        /// </summary>
        internal static string GetSelected {
            get {
                return ResourceManager.GetString("GetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        internal static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDMI音频分离.
        /// </summary>
        internal static string HDMIAudioSep {
            get {
                return ResourceManager.GetString("HDMIAudioSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit HexCode.
        /// </summary>
        internal static string HexCode {
            get {
                return ResourceManager.GetString("HexCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC Card.
        /// </summary>
        internal static string ICCard {
            get {
                return ResourceManager.GetString("ICCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Name.
        /// </summary>
        internal static string InsName {
            get {
                return ResourceManager.GetString("InsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutes.
        /// </summary>
        internal static string Institutes {
            get {
                return ResourceManager.GetString("Institutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入输出.
        /// </summary>
        internal static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启I0检测开机.
        /// </summary>
        internal static string IOBoot {
            get {
                return ResourceManager.GetString("IOBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启I0检测关机.
        /// </summary>
        internal static string IOShutDown {
            get {
                return ResourceManager.GetString("IOShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Feed.
        /// </summary>
        internal static string LiveFeed {
            get {
                return ResourceManager.GetString("LiveFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        internal static string loginAccount {
            get {
                return ResourceManager.GetString("loginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs for Cards Scanned!!.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Devices Details(Add,Edit,Delete).
        /// </summary>
        internal static string ManageDevice {
            get {
                return ResourceManager.GetString("ManageDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max File Size allowed to upload is 500 MB.
        /// </summary>
        internal static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Signal.
        /// </summary>
        internal static string MediaSignal {
            get {
                return ResourceManager.GetString("MediaSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberID.
        /// </summary>
        internal static string MemberID {
            get {
                return ResourceManager.GetString("MemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methanal Level.
        /// </summary>
        internal static string Methanal {
            get {
                return ResourceManager.GetString("Methanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string Mins {
            get {
                return ResourceManager.GetString("Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name:.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Row.
        /// </summary>
        internal static string NewRow {
            get {
                return ResourceManager.GetString("NewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have a local account..
        /// </summary>
        internal static string noAccount {
            get {
                return ResourceManager.GetString("noAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files uploaded.
        /// </summary>
        internal static string NoFileUpload {
            get {
                return ResourceManager.GetString("NoFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pending Request.
        /// </summary>
        internal static string NoPending {
            get {
                return ResourceManager.GetString("NoPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd.
        /// </summary>
        internal static string Odd {
            get {
                return ResourceManager.GetString("Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok(Hexadecimal code).
        /// </summary>
        internal static string OkHex {
            get {
                return ResourceManager.GetString("OkHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On(Hexadecimal code).
        /// </summary>
        internal static string OnHex {
            get {
                return ResourceManager.GetString("OnHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        internal static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Power Satus.
        /// </summary>
        internal static string PCPower {
            get {
                return ResourceManager.GetString("PCPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Uses.
        /// </summary>
        internal static string PCUses {
            get {
                return ResourceManager.GetString("PCUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Access(For).
        /// </summary>
        internal static string PendingAccess {
            get {
                return ResourceManager.GetString("PendingAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Person.
        /// </summary>
        internal static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        internal static string PhoneVerify {
            get {
                return ResourceManager.GetString("PhoneVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podium Lock Status.
        /// </summary>
        internal static string PodiumLock {
            get {
                return ResourceManager.GetString("PodiumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port No.
        /// </summary>
        internal static string PortNo {
            get {
                return ResourceManager.GetString("PortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影机关发2次232码.
        /// </summary>
        internal static string Proj232 {
            get {
                return ResourceManager.GetString("Proj232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影机自动开机.
        /// </summary>
        internal static string ProjAutoBoot {
            get {
                return ResourceManager.GetString("ProjAutoBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影机自动关机.
        /// </summary>
        internal static string ProjAutoShut {
            get {
                return ResourceManager.GetString("ProjAutoShut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影机自动切换.
        /// </summary>
        internal static string ProjAutoSwitch {
            get {
                return ResourceManager.GetString("ProjAutoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projector.
        /// </summary>
        internal static string Projector {
            get {
                return ResourceManager.GetString("Projector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影机开机延时.
        /// </summary>
        internal static string ProjectorDelayBoot {
            get {
                return ResourceManager.GetString("ProjectorDelayBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影机关机延时.
        /// </summary>
        internal static string projectorDelayShut {
            get {
                return ResourceManager.GetString("projectorDelayShut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projector Used Hours.
        /// </summary>
        internal static string ProjectorHours {
            get {
                return ResourceManager.GetString("ProjectorHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projector Power Status.
        /// </summary>
        internal static string ProjectorPower {
            get {
                return ResourceManager.GetString("ProjectorPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projector Uses.
        /// </summary>
        internal static string ProjectorUses {
            get {
                return ResourceManager.GetString("ProjectorUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投影机关发2次红外码.
        /// </summary>
        internal static string ProjInfraRed {
            get {
                return ResourceManager.GetString("ProjInfraRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projector OFF.
        /// </summary>
        internal static string ProjOff {
            get {
                return ResourceManager.GetString("ProjOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projector ON.
        /// </summary>
        internal static string ProjOn {
            get {
                return ResourceManager.GetString("ProjOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read configuration settings.
        /// </summary>
        internal static string ReadConfig {
            get {
                return ResourceManager.GetString("ReadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall.
        /// </summary>
        internal static string Recall {
            get {
                return ResourceManager.GetString("Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off Recording.
        /// </summary>
        internal static string RecordingOff {
            get {
                return ResourceManager.GetString("RecordingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On Recording.
        /// </summary>
        internal static string RecordingOn {
            get {
                return ResourceManager.GetString("RecordingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Per Page!!.
        /// </summary>
        internal static string RecordsPerPage {
            get {
                return ResourceManager.GetString("RecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Here.
        /// </summary>
        internal static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        internal static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Users.
        /// </summary>
        internal static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveHex {
            get {
                return ResourceManager.GetString("SaveHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Card.
        /// </summary>
        internal static string ScanCard {
            get {
                return ResourceManager.GetString("ScanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Scan Card and Add User Details.
        /// </summary>
        internal static string ScanCardPara1 {
            get {
                return ResourceManager.GetString("ScanCardPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the card is scanned, a table to add the user data will appear. After adding all the details, click &apos;OK&apos;..
        /// </summary>
        internal static string ScanCardPara2 {
            get {
                return ResourceManager.GetString("ScanCardPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Access to User.
        /// </summary>
        internal static string ScanCardPara3 {
            get {
                return ResourceManager.GetString("ScanCardPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After completing step 1, you can give access to User and Register the card..
        /// </summary>
        internal static string ScanCardPara4 {
            get {
                return ResourceManager.GetString("ScanCardPara4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select access level and options from the Select Access link in the table. Click on Register to register the card.
        /// </summary>
        internal static string ScanCardPara5 {
            get {
                return ResourceManager.GetString("ScanCardPara5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Card Status.
        /// </summary>
        internal static string ScanCardPara6 {
            get {
                return ResourceManager.GetString("ScanCardPara6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the current status of card(s) that you register..
        /// </summary>
        internal static string ScanCardPara7 {
            get {
                return ResourceManager.GetString("ScanCardPara7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might want to check if the scanned card is registered to all locations or is in pending state. You can check and try to update it.
        /// </summary>
        internal static string ScanCardPara8 {
            get {
                return ResourceManager.GetString("ScanCardPara8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Down.
        /// </summary>
        internal static string SCDown {
            get {
                return ResourceManager.GetString("SCDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统开启时降幕.
        /// </summary>
        internal static string ScDownProj {
            get {
                return ResourceManager.GetString("ScDownProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用投影仪打开数字屏幕.
        /// </summary>
        internal static string ScreenDownWithProj {
            get {
                return ResourceManager.GetString("ScreenDownWithProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幕布联动投影机关.
        /// </summary>
        internal static string ScreenUPWithProj {
            get {
                return ResourceManager.GetString("ScreenUPWithProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digital Screen Status.
        /// </summary>
        internal static string SCStatus {
            get {
                return ResourceManager.GetString("SCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Access.
        /// </summary>
        internal static string SelectAccess {
            get {
                return ResourceManager.GetString("SelectAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Class for Configuration Setting.
        /// </summary>
        internal static string SelectClassConfig {
            get {
                return ResourceManager.GetString("SelectClassConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Institute and Grade.
        /// </summary>
        internal static string SelectInsGrade {
            get {
                return ResourceManager.GetString("SelectInsGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Institute.
        /// </summary>
        internal static string SelectInstitute {
            get {
                return ResourceManager.GetString("SelectInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Locations.
        /// </summary>
        internal static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLEEP.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string Sno {
            get {
                return ResourceManager.GetString("Sno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Camera.
        /// </summary>
        internal static string StudentCam {
            get {
                return ResourceManager.GetString("StudentCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull!!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷卡关.
        /// </summary>
        internal static string SwipeClose {
            get {
                return ResourceManager.GetString("SwipeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷卡开.
        /// </summary>
        internal static string SwipeOpen {
            get {
                return ResourceManager.GetString("SwipeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统报警.
        /// </summary>
        internal static string SystemAlarm {
            get {
                return ResourceManager.GetString("SystemAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off System.
        /// </summary>
        internal static string SystemHexOff {
            get {
                return ResourceManager.GetString("SystemHexOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On System.
        /// </summary>
        internal static string SystemHexOn {
            get {
                return ResourceManager.GetString("SystemHexOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System lock Status.
        /// </summary>
        internal static string SystemLock {
            get {
                return ResourceManager.GetString("SystemLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string SystemSetup {
            get {
                return ResourceManager.GetString("SystemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Camera.
        /// </summary>
        internal static string TeacherCam {
            get {
                return ResourceManager.GetString("TeacherCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature, Humidity &amp; PM(Particulate Matter) Graph for.
        /// </summary>
        internal static string TempratureChartHead {
            get {
                return ResourceManager.GetString("TempratureChartHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Service.
        /// </summary>
        internal static string TimerService {
            get {
                return ResourceManager.GetString("TimerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change location access.
        /// </summary>
        internal static string ToolTipLocation {
            get {
                return ResourceManager.GetString("ToolTipLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend to Register.
        /// </summary>
        internal static string ToolTipResend {
            get {
                return ResourceManager.GetString("ToolTipResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启蜂鸣器.
        /// </summary>
        internal static string TurnOnBuzzer {
            get {
                return ResourceManager.GetString("TurnOnBuzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        internal static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId / Phone No..
        /// </summary>
        internal static string UserPhone {
            get {
                return ResourceManager.GetString("UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersMenu {
            get {
                return ResourceManager.GetString("UsersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        internal static string ValidNo {
            get {
                return ResourceManager.GetString("ValidNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        internal static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启音量记忆.
        /// </summary>
        internal static string VolumeOn {
            get {
                return ResourceManager.GetString("VolumeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Status.
        /// </summary>
        internal static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write configuration settings.
        /// </summary>
        internal static string WriteConfig {
            get {
                return ResourceManager.GetString("WriteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        internal static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
